controller_frequency: 10.0
recovery_behaviour_enabled: true

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 4.2

  max_vel_x: 1.5
  min_vel_x: 0.01
  # max_vel_y: 0
  # min_vel_y: 0

  # max_vel_trans: 0.4
  # min_vel_trans: 0
  max_vel_theta: 4.0  #4
  min_vel_theta: 0.63  #0.61

  path_distance_bias: 1.0
  goal_distance_bias: 0.7 #0.75
  occdist_scale: 0.013 #0.0129

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 1.0
  #latch_xy_goal_tolerance: false
  # min_in_place_vel_theta: 2.0
  # max_in_place_vel_theta: 5.0
  #forward_point_distance: 0
  holonomic_robot: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_theta:  3.2

  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 2.0