gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger1_joint
    # - gripper_finger1_finger_tip_joint
    # - gripper_finger2_joint
    # - gripper_finger2_finger_tip_joint

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10